ctl:
  plugins:

    - type: command
      name: printenv
      config:
        shell: true
        command:
          - "echo \"ctx.home: {{ ctx.home }}\""
          - "echo \"ctx.tmpdir: {{ ctx.tmpdir }}\""
          - "echo \"ctx.cachedir: {{ ctx.cachedir }}\""
          - "echo \"ctx.userhome: {{ ctx.userhome }}\""
          - "echo \"{{ input.plugin }}\""
          - "echo \"{{ plugin.git_template }}\""
          - "echo \"{{ plugin.copy }}\""
          - "echo \"{{ ctx.config }}\""

    - name: git_template
      type: git
      config:
        repo_url: git@github.com:egfrank/Mock-Template

    - name: template
      type: template
      config:
        # template root directory (path)
        source: {{ ctx.cachedir }}/github.com/egfrank/Mock-Template
        # template output directory (path)
        output: output
        walk_dirs:
          - Ctl
          - Base
        vars:
          - Ctl/tmplvars.yaml
        # ignore:
        #   - \.sh$

    # chain plugin
    - name: chain_template
      type: chain
      config:
        chain:
          - stage: git_clone
            plugin: git_template
            action:
              name: clone

          - stage: git_pull
            plugin: git_template
            action:
              name: pull

          - stage: template
            plugin: template

    - name: delete
      type: command
      config:
        shell: true
        command:
          - rm -rf output
  permissions:
    - namespace: ctl
      permission: crud
