ctl:
  plugins:

    - type: command
      name: printenv
      config:
        shell: true
        command:
          - "echo \"ctx.home: {{ ctx.home }}\""
          - "echo \"ctx.tmpdir: {{ ctx.tmpdir }}\""
          - "echo \"ctx.cachedir: {{ ctx.cachedir }}\""
          - "echo \"ctx.userhome: {{ ctx.userhome }}\""
          - "echo \"{{ input.plugin }}\""
          - "echo \"{{ plugin.git_template }}\""
          - "echo \"{{ plugin.copy }}\""
          - "echo \"{{ ctx.config }}\""

    - name: git_template
      type: git
      config:
        repo_url: git@github.com:egfrank/Mock-Template

    - name: template
      type: template
      config:
        # template root directory (path)
        source: {{ ctx.cachedir }}/github.com/egfrank/Mock-Template
        # template output directory (path)
        output: {{ ctx.home }}/..
        walk_dirs:
          - Ctl
          - Base
        vars:
          - Ctl/tmplvars.yaml
        ignore:
          - .git$

    # chain plugin
    - name: chain_template
      type: chain
      config:
        chain:
          - stage: git_clone
            plugin: git_template
            action:
              name: clone

          - stage: git_pull
            plugin: git_template
            action:
              name: pull

          - stage: template
            plugin: template

          - stage: move
            plugin: move

          - stage: clean
            plugin: clean

    - name: move
      type: command
      config:
        shell: true
        command:
          - mv -vn Base/* Base/.* .

    - name: clean
      type: command
      config:
        shell: true
        command:
          - rm -rf Base Ctl/tmp

    - name: reset
      type: command
      config:
        shell: true
        command:
          - rm -rf Ctl/dev Ctl/docker Ctl/tmp Base tox.ini
  permissions:
    - namespace: ctl
      permission: crud
